Switched to pack based approach in an attempt to workaround the pack issue.  Realized that the issue is that re-packing is never going to work as it is, so will revert to object move approach next.  Also realized that pruning must be done manually since the expire date used through "git gc" means the alternate will be gone by the time pruning happens.

diff --git a/scripts/git-rm-blobs b/scripts/git-rm-blobs
--- a/scripts/git-rm-blobs
+++ b/scripts/git-rm-blobs
@@ -27,31 +27,35 @@ revlist="$@"
 ## may be worth it.  Otherwise just the the blob moving approach.
 
 ## Use a pack to move objects to the alternate store
-#git-get-blobs --unpacked $revlist | git pack-objects blobs
+git list-objects blob --unpacked $revlist | git pack-objects blobs
 ## Move the pack to the alternate object store
-# pack=$(ls -d blobs-????????????????????????????????????????.pack)
-# hash=${pack:6:40}
-# mv $pack blobs-$hash.idx $GIT_DIR/archive/pack/
+pack=$(ls -d blobs-????????????????????????????????????????.pack)
+hash=${pack:6:40}
+mkdir -p $GIT_DIR/archive/pack/
+mv $pack blobs-$hash.idx $GIT_DIR/archive/pack/
 
 ## Manually move objects to the alternate store
-blobs=$(git-get-blobs --unpacked $revlist)
-for blob in $blobs
-do
-    mkdir -p $GIT_DIR/archive/${blob:0:2}
-    mv $GIT_OBJECT_DIRECTORY/${blob:0:2}/${blob:2:38} $GIT_DIR/archive/${blob:0:2}/
-done
+# blobs=$(git-get-blobs --unpacked $revlist)
+# for blob in $blobs
+# do
+#     mkdir -p $GIT_DIR/archive/${blob:0:2}
+#     mv $GIT_OBJECT_DIRECTORY/${blob:0:2}/${blob:2:38} $GIT_DIR/archive/${blob:0:2}/
+# done
 
 ## remove the objects form the local store
-git gc --auto || ( die "Garbage collection failed" )
+## Since we next remove the alternate that would make the objects
+## prunable, we have to force pruning now.  The auto expire will leave
+## the objects behind.
+git prune || ( die "Pruning failed" )
 
 ## Remove the pack but leave the index
-# rm -f $GIT_DIR/archive/pack/$pack
+rm -f $GIT_DIR/archive/pack/$pack
 
 ## Remove the successfully archived objects from the alternate store
 ## At this point they're no longer available to the repo but safely
 ## backed up in the bundle
-for blob in $blobs
-do
-    rm -f $GIT_DIR/archive/${blob:0:2}/${blob:2:38}
-    rmdir --ignore-fail-on-non-empty $GIT_DIR/archive/${blob:0:2}
-done
+# for blob in $blobs
+# do
+#     rm -f $GIT_DIR/archive/${blob:0:2}/${blob:2:38}
+#     rmdir --ignore-fail-on-non-empty $GIT_DIR/archive/${blob:0:2}
+# done
